# Generated by Django 4.2.13 on 2024-06-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_book_book_photos_delete_bookphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_en', models.ImageField(blank=True, null=True, upload_to='carousel_images/en/')),
                ('image_ru', models.ImageField(blank=True, null=True, upload_to='carousel_images/ru/')),
                ('image_uz', models.ImageField(blank=True, null=True, upload_to='carousel_images/uz/')),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_uz', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
