# Generated by Django 4.2.13 on 2024-07-10 05:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp',
            field=models.CharField(default=api.models.generate_otp, max_length=4),
        ),
    ]
