# Generated by Django 4.2.13 on 2024-06-20 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_book_book_author_remove_book_book_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='covers/'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='book_language',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='book_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='book_pages_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='book_photos',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='book',
            name='book_publisher',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='book',
            name='book_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='book_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='api.author'),
        ),
    ]
