# Generated by Django 4.2.13 on 2024-06-20 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_category_book_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_photos',
        ),
        migrations.CreateModel(
            name='BookPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.book')),
            ],
        ),
    ]
