# Generated by Django 4.2.13 on 2024-06-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_book_book_photos_bookphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_photos',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.DeleteModel(
            name='BookPhoto',
        ),
    ]
